### ISSUE TITLE
install run demo

### ISSUE THREAD

**Issue by mhanuel26** [szhsin/react-menu#624]
Hi, 

I might be doing something wrong, but I am getting error to start the demo, this is what I am doing,

```
mhanuel@mhanuel-MSI:~/devel/React/react-menu/example$ yarn add @szhsin/react-menu
yarn add v1.22.19
warning ../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-config-next@12.2.5" has unmet peer dependency "eslint@^7.23.0 || ^8.0.0".
warning "eslint-config-next > @typescript-eslint/parser@5.35.1" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "eslint-config-next > eslint-import-resolver-typescript@2.7.1" has unmet peer dependency "eslint@*".
warning "eslint-config-next > eslint-plugin-import@2.26.0" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".
warning "eslint-config-next > eslint-plugin-jsx-a11y@6.6.1" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
warning "eslint-config-next > eslint-plugin-react@7.31.0" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
warning "eslint-config-next > eslint-plugin-react-hooks@4.6.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @szhsin/react-menu@3.1.2
info All dependencies
└─ @szhsin/react-menu@3.1.2
Done in 2.57s.
mhanuel@mhanuel-MSI:~/devel/React/react-menu/example$ yarn install
yarn install v1.22.19
warning ../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.08s.
mhanuel@mhanuel-MSI:~/devel/React/react-menu/example$ yarn start
yarn run v1.22.19
warning ../../package.json: No license field
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Cannot find module '/home/mhanuel/devel/React/react-menu/example/.next/prerender-manifest.json'
Require stack:
- /home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/next-server.js
- /home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/next.js
- /home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/lib/start-server.js
- /home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/cli/next-start.js
- /home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/lib/commands.js
- /home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at mod._resolveFilename (/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at NextNodeServer.getPrerenderManifest (/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/next-server.js:1035:26)
    at NextNodeServer.getPreviewProps (/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/base-server.js:361:21)
    at new Server (/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/base-server.js:79:32)
    at new NextNodeServer (/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/next-server.js:63:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/next-server.js',
    '/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/next.js',
    '/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/server/lib/start-server.js',
    '/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/cli/next-start.js',
    '/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/lib/commands.js',
    '/home/mhanuel/devel/React/react-menu/example/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

would you mind to help me please.

Thanks

**Comment by szhsin** [comment]
Hi @mhanuel26 , the example project has already been set up for local development with the main repo, so it's not necessary to run `yarn add @szhsin/react-menu` or `npm i @szhsin/react-menu`. 
Personally I use `npm` instead of `yarn` as package manager.

When you're in the example folder, simply run `npm install` and then `npm run dev`, which will spin up a local dev server.
It's a standard Nextjs project and more scripts can be found in the package.json file.
Hope this can be helpful.
