### ISSUE TITLE
Getting error when using Button from third-party component library

### ISSUE THREAD

**Issue by ericxinzhang** [szhsin/react-menu#693]
React/React-dom version: 18.2.0
React-Menu version: 3.2.0

I am asked to use [Icon button](https://cloudscape.design/components/button/?tabId=playground&example=inline-icon-button) from [cloudscape component library](https://cloudscape.design/components/overview/).

My code snippet is as follows:
```
    <Menu menuButton={<Button ariaLabel="add-new-item" iconName="add-plus" variant="inline-icon"/>}>
      <MenuItem>New File</MenuItem>
      <MenuItem>Save</MenuItem>
   </Menu>
```
It renders properly, however when I click on the button the following error occurred:

```
positionMenu.js:28 Uncaught TypeError: anchorRef.current.getBoundingClientRect is not a function
    at positionMenu (positionMenu.js:28:1)
    at MenuList.js:178:1
    at MenuList.js:248:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)
    at commitLayoutEffects (react-dom.development.js:24612:1)
    at commitRootImpl (react-dom.development.js:26823:1)
```

Any idea how I can work around? I tried normal `<button>` and it works fine but it'd be great if I could use the button from the lib so as to keep UX consistency.

**Comment by szhsin** [comment]
Hi @ericxinzhang , this is usually because the `Button` component from the UI library doesn't implement ref forwarding. You can wrap the component within a `div`:
```jsx
<Menu
  menuButton={
    <div style={{ display: "inline-block" }}>
      <Button
        ariaLabel="add-new-item"
        iconName="add-plus"
        variant="inline-icon"
      />
    </div>
  }
>
  <MenuItem>New File</MenuItem>
  <MenuItem>Save</MenuItem>
</Menu>
```


Alternatively, you might create a reusable wrapper component of the Button:
```jsx
const MenuButton = React.forwardRef((props, ref) => (
  <div ref={ref} style={{ display: "inline-block" }}>
    <Button {...props} />
  </div>
));
``` 
then use it normally:
```jsx
<Menu
  menuButton={
    <MenuButton
      ariaLabel="add-new-item"
      iconName="add-plus"
      variant="inline-icon"
    />
  }
>
  <MenuItem>New File</MenuItem>
  <MenuItem>Save</MenuItem>
</Menu>
```
